{\rtf1\ansi\ansicpg1252\cocoartf1038\cocoasubrtf360
{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;}
{\*\listtable{\list\listtemplateid1\listhybrid{\listlevel\levelnfc0\levelnfcn0\leveljc0\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\*\levelmarker \{decimal\}.}{\leveltext\leveltemplateid1\'02\'00.;}{\levelnumbers\'01;}\fi-360\li720\lin720 }{\listname ;}\listid1}}
{\*\listoverridetable{\listoverride\listid1\listoverridecount0\ls1}}
\margl1440\margr1440\vieww9000\viewh8400\viewkind0
\deftab720
\pard\tx220\tx720\pardeftab720\li720\fi-720\ql\qnatural
\ls1\ilvl0
\f0\fs24 \cf0 {\listtext	1.	}Page \{\
{\listtext	2.	}\'a0 \'a0 id: mainPage\
{\listtext	3.	}\'a0\
{\listtext	4.	}\'a0 \'a0 Button \{\
{\listtext	5.	}\'a0 \'a0 \'a0 \'a0 id: button1\
{\listtext	6.	}\'a0 \'a0 \'a0 \'a0 x: 16\
{\listtext	7.	}\'a0 \'a0 \'a0 \'a0 y: 324\
{\listtext	8.	}\'a0 \'a0 \'a0 \'a0 width: 100\
{\listtext	9.	}\'a0 \'a0 \'a0 \'a0 height: 42\
{\listtext	10.	}\'a0 \'a0 \'a0 \'a0 text: "Play"\
{\listtext	11.	}\'a0 \'a0 \'a0 \'a0 onClicked:\
{\listtext	12.	}\'a0 \'a0 \'a0 \'a0 \'a0 \'a0 AudioToggle.play()\
{\listtext	13.	}\'a0 \'a0 \}\
{\listtext	14.	}\'a0\
{\listtext	15.	}\'a0 \'a0 Button \{\
{\listtext	16.	}\'a0 \'a0 \'a0 \'a0 id: button2\
{\listtext	17.	}\'a0 \'a0 \'a0 \'a0 x: 126\
{\listtext	18.	}\'a0 \'a0 \'a0 \'a0 y: 324\
{\listtext	19.	}\'a0 \'a0 \'a0 \'a0 width: 100\
{\listtext	20.	}\'a0 \'a0 \'a0 \'a0 height: 42\
{\listtext	21.	}\'a0 \'a0 \'a0 \'a0 text: "Stop"\
{\listtext	22.	}\'a0 \'a0 \'a0 \'a0 onClicked:\
{\listtext	23.	}\'a0 \'a0 \'a0 \'a0 \'a0 \'a0 AudioToggle.stop()\
{\listtext	24.	}\'a0 \'a0 \}\
{\listtext	25.	}\'a0\
{\listtext	26.	}\'a0 \'a0 Button \{\
{\listtext	27.	}\'a0 \'a0 \'a0 \'a0 id: button3\
{\listtext	28.	}\'a0 \'a0 \'a0 \'a0 x: 247\
{\listtext	29.	}\'a0 \'a0 \'a0 \'a0 y: 324\
{\listtext	30.	}\'a0 \'a0 \'a0 \'a0 width: 100\
{\listtext	31.	}\'a0 \'a0 \'a0 \'a0 height: 42\
{\listtext	32.	}\'a0 \'a0 \'a0 \'a0 text: "Record"\
{\listtext	33.	}\'a0 \'a0 \'a0 \'a0 onClicked:\
{\listtext	34.	}\'a0 \'a0 \'a0 \'a0 \'a0 \'a0 AudioToggle.record()\
{\listtext	35.	}\'a0 \'a0 \}\
{\listtext	36.	}\'a0\
{\listtext	37.	}\}\
}